/* GENERATED by tools/gen_runtime_events_usdt.py -- DO NOT EDIT.
 * Regenerate after changing the enums in runtime_events.h. */

#ifndef CAML_RUNTIME_EVENTS_USDT_H
#define CAML_RUNTIME_EVENTS_USDT_H

/* USDT (SystemTap SDT) probes for the runtime event surface.
 *
 * Every probe is static and individually addressable: each call site
 * names its phase as a literal, so CAML_EV_BEGIN(EV_MINOR) pastes into a
 * probe called "minor_begin" rather than one generic probe taking the
 * phase as an argument. That is what lets a tracer attach to just the
 * probes it wants:
 *
 *   bpftrace -l 'usdt:./prog:ocaml:*'            all probes
 *   bpftrace -l 'usdt:./prog:ocaml:minor*'       minor-GC phases
 *   bpftrace -l 'usdt:./prog:ocaml:counter_*'    counters
 *   bpftrace -l 'usdt:./prog:ocaml:lifecycle_*'  lifecycle events
 *
 * When no tracer is attached each probe is a single 1-byte nop and
 * costs ~0.11 ns; arguments generate no marshalling code at all, their
 * locations being recorded in the ELF note. When attached, a hit costs
 * ~1.8 us (a uprobe trap), so probes must stay off any path that fires
 * at more than order 100k/s. See PLAN-ocaml-usdt.md step 0 for the
 * measurements behind those numbers.
 */

#if defined(HAS_SYS_SDT_H) && !defined(CAML_DISABLE_USDT)

#include <sys/sdt.h>

#define CAML_USDT_ENABLED 1

/* Two-level paste so the name-mapping macro below is expanded before
 * being glued to its _begin/_end suffix. */
#define CAML_USDT_CAT_(a, b) a##b
#define CAML_USDT_CAT(a, b) CAML_USDT_CAT_(a, b)

/* Enum constant -> probe name stem. */
#define CAML_USDT_PHASE_EV_EXPLICIT_GC_SET explicit_gc_set
#define CAML_USDT_PHASE_EV_EXPLICIT_GC_STAT explicit_gc_stat
#define CAML_USDT_PHASE_EV_EXPLICIT_GC_MINOR explicit_gc_minor
#define CAML_USDT_PHASE_EV_EXPLICIT_GC_MAJOR explicit_gc_major
#define CAML_USDT_PHASE_EV_EXPLICIT_GC_FULL_MAJOR explicit_gc_full_major
#define CAML_USDT_PHASE_EV_EXPLICIT_GC_COMPACT explicit_gc_compact
#define CAML_USDT_PHASE_EV_MAJOR major
#define CAML_USDT_PHASE_EV_MAJOR_SWEEP major_sweep
#define CAML_USDT_PHASE_EV_MAJOR_MARK_ROOTS major_mark_roots
#define CAML_USDT_PHASE_EV_MAJOR_MEMPROF_ROOTS major_memprof_roots
#define CAML_USDT_PHASE_EV_MAJOR_MARK major_mark
#define CAML_USDT_PHASE_EV_MINOR minor
#define CAML_USDT_PHASE_EV_MINOR_LOCAL_ROOTS minor_local_roots
#define CAML_USDT_PHASE_EV_MINOR_MEMPROF_ROOTS minor_memprof_roots
#define CAML_USDT_PHASE_EV_MINOR_MEMPROF_CLEAN minor_memprof_clean
#define CAML_USDT_PHASE_EV_MINOR_FINALIZED minor_finalized
#define CAML_USDT_PHASE_EV_EXPLICIT_GC_MAJOR_SLICE explicit_gc_major_slice
#define CAML_USDT_PHASE_EV_FINALISE_UPDATE_FIRST finalise_update_first
#define CAML_USDT_PHASE_EV_FINALISE_UPDATE_LAST finalise_update_last
#define CAML_USDT_PHASE_EV_INTERRUPT_REMOTE interrupt_remote
#define CAML_USDT_PHASE_EV_MAJOR_EPHE_MARK major_ephe_mark
#define CAML_USDT_PHASE_EV_MAJOR_EPHE_SWEEP major_ephe_sweep
#define CAML_USDT_PHASE_EV_MAJOR_FINISH_MARKING major_finish_marking
#define CAML_USDT_PHASE_EV_MAJOR_GC_CYCLE_DOMAINS major_gc_cycle_domains
#define CAML_USDT_PHASE_EV_MAJOR_GC_PHASE_CHANGE major_gc_phase_change
#define CAML_USDT_PHASE_EV_MAJOR_GC_STW major_gc_stw
#define CAML_USDT_PHASE_EV_MAJOR_MARK_OPPORTUNISTIC major_mark_opportunistic
#define CAML_USDT_PHASE_EV_MAJOR_SLICE major_slice
#define CAML_USDT_PHASE_EV_MAJOR_FINISH_CYCLE major_finish_cycle
#define CAML_USDT_PHASE_EV_MINOR_CLEAR minor_clear
#define CAML_USDT_PHASE_EV_MINOR_FINALIZERS_OLDIFY minor_finalizers_oldify
#define CAML_USDT_PHASE_EV_MINOR_GLOBAL_ROOTS minor_global_roots
#define CAML_USDT_PHASE_EV_MINOR_LEAVE_BARRIER minor_leave_barrier
#define CAML_USDT_PHASE_EV_STW_API_BARRIER stw_api_barrier
#define CAML_USDT_PHASE_EV_STW_HANDLER stw_handler
#define CAML_USDT_PHASE_EV_STW_LEADER stw_leader
#define CAML_USDT_PHASE_EV_MAJOR_FINISH_SWEEPING major_finish_sweeping
#define CAML_USDT_PHASE_EV_MAJOR_MEMPROF_CLEAN major_memprof_clean
#define CAML_USDT_PHASE_EV_MINOR_FINALIZERS_ADMIN minor_finalizers_admin
#define CAML_USDT_PHASE_EV_MINOR_REMEMBERED_SET minor_remembered_set
#define CAML_USDT_PHASE_EV_MINOR_REMEMBERED_SET_PROMOTE minor_remembered_set_promote
#define CAML_USDT_PHASE_EV_MINOR_LOCAL_ROOTS_PROMOTE minor_local_roots_promote
#define CAML_USDT_PHASE_EV_DOMAIN_CONDITION_WAIT domain_condition_wait
#define CAML_USDT_PHASE_EV_DOMAIN_RESIZE_HEAP_RESERVATION domain_resize_heap_reservation
#define CAML_USDT_PHASE_EV_COMPACT compact
#define CAML_USDT_PHASE_EV_COMPACT_EVACUATE compact_evacuate
#define CAML_USDT_PHASE_EV_COMPACT_FORWARD compact_forward
#define CAML_USDT_PHASE_EV_COMPACT_RELEASE compact_release
#define CAML_USDT_PHASE_EV_EMPTY_MINOR empty_minor
#define CAML_USDT_PHASE_EV_MINOR_EPHE_CLEAN minor_ephe_clean

#define CAML_USDT_COUNTER_EV_C_FORCE_MINOR_ALLOC_SMALL counter_force_minor_alloc_small
#define CAML_USDT_COUNTER_EV_C_FORCE_MINOR_MAKE_VECT counter_force_minor_make_vect
#define CAML_USDT_COUNTER_EV_C_FORCE_MINOR_SET_MINOR_HEAP_SIZE counter_force_minor_set_minor_heap_size
#define CAML_USDT_COUNTER_EV_C_FORCE_MINOR_MEMPROF counter_force_minor_memprof
#define CAML_USDT_COUNTER_EV_C_MINOR_PROMOTED counter_minor_promoted
#define CAML_USDT_COUNTER_EV_C_MINOR_ALLOCATED counter_minor_allocated
#define CAML_USDT_COUNTER_EV_C_REQUEST_MAJOR_ALLOC_SHR counter_request_major_alloc_shr
#define CAML_USDT_COUNTER_EV_C_REQUEST_MAJOR_ADJUST_GC_SPEED counter_request_major_adjust_gc_speed
#define CAML_USDT_COUNTER_EV_C_REQUEST_MINOR_REALLOC_REF_TABLE counter_request_minor_realloc_ref_table
#define CAML_USDT_COUNTER_EV_C_REQUEST_MINOR_REALLOC_EPHE_REF_TABLE counter_request_minor_realloc_ephe_ref_table
#define CAML_USDT_COUNTER_EV_C_REQUEST_MINOR_REALLOC_CUSTOM_TABLE counter_request_minor_realloc_custom_table
#define CAML_USDT_COUNTER_EV_C_MAJOR_HEAP_POOL_WORDS counter_major_heap_pool_words
#define CAML_USDT_COUNTER_EV_C_MAJOR_HEAP_POOL_LIVE_WORDS counter_major_heap_pool_live_words
#define CAML_USDT_COUNTER_EV_C_MAJOR_HEAP_LARGE_WORDS counter_major_heap_large_words
#define CAML_USDT_COUNTER_EV_C_MAJOR_HEAP_POOL_FRAG_WORDS counter_major_heap_pool_frag_words
#define CAML_USDT_COUNTER_EV_C_MAJOR_HEAP_POOL_LIVE_BLOCKS counter_major_heap_pool_live_blocks
#define CAML_USDT_COUNTER_EV_C_MAJOR_HEAP_LARGE_BLOCKS counter_major_heap_large_blocks
#define CAML_USDT_COUNTER_EV_C_MAJOR_HEAP_WORDS counter_major_heap_words
#define CAML_USDT_COUNTER_EV_C_MAJOR_ALLOCATED_WORDS counter_major_allocated_words
#define CAML_USDT_COUNTER_EV_C_MAJOR_ALLOCATED_WORK counter_major_allocated_work
#define CAML_USDT_COUNTER_EV_C_MAJOR_DEPENDENT_WORK counter_major_dependent_work
#define CAML_USDT_COUNTER_EV_C_MAJOR_EXTRA_WORK counter_major_extra_work
#define CAML_USDT_COUNTER_EV_C_MAJOR_WORK_COUNTER counter_major_work_counter
#define CAML_USDT_COUNTER_EV_C_MAJOR_ALLOC_COUNTER counter_major_alloc_counter
#define CAML_USDT_COUNTER_EV_C_MAJOR_SLICE_TARGET counter_major_slice_target
#define CAML_USDT_COUNTER_EV_C_MAJOR_SLICE_BUDGET counter_major_slice_budget
#define CAML_USDT_COUNTER_EV_C_MINOR_ALLOCATED_WORDS counter_minor_allocated_words
#define CAML_USDT_COUNTER_EV_C_MINOR_PROMOTED_WORDS counter_minor_promoted_words

#define CAML_USDT_LIFECYCLE_EV_RING_START lifecycle_ring_start
#define CAML_USDT_LIFECYCLE_EV_RING_STOP lifecycle_ring_stop
#define CAML_USDT_LIFECYCLE_EV_RING_PAUSE lifecycle_ring_pause
#define CAML_USDT_LIFECYCLE_EV_RING_RESUME lifecycle_ring_resume
#define CAML_USDT_LIFECYCLE_EV_FORK_PARENT lifecycle_fork_parent
#define CAML_USDT_LIFECYCLE_EV_FORK_CHILD lifecycle_fork_child
#define CAML_USDT_LIFECYCLE_EV_DOMAIN_SPAWN lifecycle_domain_spawn
#define CAML_USDT_LIFECYCLE_EV_DOMAIN_TERMINATE lifecycle_domain_terminate

#define CAML_USDT_EV_BEGIN(p) \
  STAP_PROBE(ocaml, CAML_USDT_CAT(CAML_USDT_PHASE_##p, _begin))
#define CAML_USDT_EV_END(p) \
  STAP_PROBE(ocaml, CAML_USDT_CAT(CAML_USDT_PHASE_##p, _end))
#define CAML_USDT_EV_COUNTER(c, v) \
  STAP_PROBE1(ocaml, CAML_USDT_CAT(CAML_USDT_COUNTER_##c, ), (v))
#define CAML_USDT_EV_LIFECYCLE(l, d) \
  STAP_PROBE1(ocaml, CAML_USDT_CAT(CAML_USDT_LIFECYCLE_##l, ), (d))

/* Dispatch for the one site that cannot name its counter as a
 * literal: realloc_generic_table() in minor_gc.c takes the counter as
 * a parameter, and its three callers pass three different ones. A
 * generated switch keeps every counter individually attachable rather
 * than collapsing those three into one generic probe. Only the arm
 * actually reached fires, and the site is cold (minor-GC table
 * growth), so the unreached nops cost nothing. */
#define CAML_USDT_EV_COUNTER_DYN(c, v) \
  do { switch (c) { \
    case EV_C_FORCE_MINOR_ALLOC_SMALL: \
      CAML_USDT_EV_COUNTER(EV_C_FORCE_MINOR_ALLOC_SMALL, (v)); break; \
    case EV_C_FORCE_MINOR_MAKE_VECT: \
      CAML_USDT_EV_COUNTER(EV_C_FORCE_MINOR_MAKE_VECT, (v)); break; \
    case EV_C_FORCE_MINOR_SET_MINOR_HEAP_SIZE: \
      CAML_USDT_EV_COUNTER(EV_C_FORCE_MINOR_SET_MINOR_HEAP_SIZE, (v)); break; \
    case EV_C_FORCE_MINOR_MEMPROF: \
      CAML_USDT_EV_COUNTER(EV_C_FORCE_MINOR_MEMPROF, (v)); break; \
    case EV_C_MINOR_PROMOTED: \
      CAML_USDT_EV_COUNTER(EV_C_MINOR_PROMOTED, (v)); break; \
    case EV_C_MINOR_ALLOCATED: \
      CAML_USDT_EV_COUNTER(EV_C_MINOR_ALLOCATED, (v)); break; \
    case EV_C_REQUEST_MAJOR_ALLOC_SHR: \
      CAML_USDT_EV_COUNTER(EV_C_REQUEST_MAJOR_ALLOC_SHR, (v)); break; \
    case EV_C_REQUEST_MAJOR_ADJUST_GC_SPEED: \
      CAML_USDT_EV_COUNTER(EV_C_REQUEST_MAJOR_ADJUST_GC_SPEED, (v)); break; \
    case EV_C_REQUEST_MINOR_REALLOC_REF_TABLE: \
      CAML_USDT_EV_COUNTER(EV_C_REQUEST_MINOR_REALLOC_REF_TABLE, (v)); break; \
    case EV_C_REQUEST_MINOR_REALLOC_EPHE_REF_TABLE: \
      CAML_USDT_EV_COUNTER(EV_C_REQUEST_MINOR_REALLOC_EPHE_REF_TABLE, (v)); break; \
    case EV_C_REQUEST_MINOR_REALLOC_CUSTOM_TABLE: \
      CAML_USDT_EV_COUNTER(EV_C_REQUEST_MINOR_REALLOC_CUSTOM_TABLE, (v)); break; \
    case EV_C_MAJOR_HEAP_POOL_WORDS: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_HEAP_POOL_WORDS, (v)); break; \
    case EV_C_MAJOR_HEAP_POOL_LIVE_WORDS: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_HEAP_POOL_LIVE_WORDS, (v)); break; \
    case EV_C_MAJOR_HEAP_LARGE_WORDS: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_HEAP_LARGE_WORDS, (v)); break; \
    case EV_C_MAJOR_HEAP_POOL_FRAG_WORDS: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_HEAP_POOL_FRAG_WORDS, (v)); break; \
    case EV_C_MAJOR_HEAP_POOL_LIVE_BLOCKS: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_HEAP_POOL_LIVE_BLOCKS, (v)); break; \
    case EV_C_MAJOR_HEAP_LARGE_BLOCKS: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_HEAP_LARGE_BLOCKS, (v)); break; \
    case EV_C_MAJOR_HEAP_WORDS: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_HEAP_WORDS, (v)); break; \
    case EV_C_MAJOR_ALLOCATED_WORDS: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_ALLOCATED_WORDS, (v)); break; \
    case EV_C_MAJOR_ALLOCATED_WORK: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_ALLOCATED_WORK, (v)); break; \
    case EV_C_MAJOR_DEPENDENT_WORK: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_DEPENDENT_WORK, (v)); break; \
    case EV_C_MAJOR_EXTRA_WORK: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_EXTRA_WORK, (v)); break; \
    case EV_C_MAJOR_WORK_COUNTER: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_WORK_COUNTER, (v)); break; \
    case EV_C_MAJOR_ALLOC_COUNTER: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_ALLOC_COUNTER, (v)); break; \
    case EV_C_MAJOR_SLICE_TARGET: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_SLICE_TARGET, (v)); break; \
    case EV_C_MAJOR_SLICE_BUDGET: \
      CAML_USDT_EV_COUNTER(EV_C_MAJOR_SLICE_BUDGET, (v)); break; \
    case EV_C_MINOR_ALLOCATED_WORDS: \
      CAML_USDT_EV_COUNTER(EV_C_MINOR_ALLOCATED_WORDS, (v)); break; \
    case EV_C_MINOR_PROMOTED_WORDS: \
      CAML_USDT_EV_COUNTER(EV_C_MINOR_PROMOTED_WORDS, (v)); break; \
    default: break; \
  } } while (0)

#else /* no <sys/sdt.h>, or USDT explicitly disabled */

/* The arguments are still evaluated: a counter value or lifecycle
 * datum may be a call with side effects, and dropping it would change
 * behaviour rather than just remove instrumentation. */
#define CAML_USDT_EV_BEGIN(p)        ((void) 0)
#define CAML_USDT_EV_END(p)          ((void) 0)
#define CAML_USDT_EV_COUNTER(c, v)   ((void) (v))
#define CAML_USDT_EV_LIFECYCLE(l, d) ((void) (d))
#define CAML_USDT_EV_COUNTER_DYN(c, v) ((void) (c), (void) (v))

#endif

#endif /* CAML_RUNTIME_EVENTS_USDT_H */
