#!/usr/bin/env python3
# Generate runtime/caml/runtime_events_usdt.h from the enums in
# runtime/caml/runtime_events.h.
#
# The USDT probe surface is derived mechanically from ev_runtime_phase,
# ev_runtime_counter and ev_lifecycle so it cannot drift from the enums: add a
# phase to the enum, re-run this, and its probes appear. Run from the tree
# root:
#
#     python3 tools/gen_runtime_events_usdt.py
#
# and commit the result. `make check-usdt-probes` verifies the checked-in
# header still matches the enums.

import re
import sys
import os

HEADER = 'runtime/caml/runtime_events.h'
OUTPUT = 'runtime/caml/runtime_events_usdt.h'
PROVIDER = 'ocaml'


def enum_members(src, name):
    """Members of `typedef enum { ... } name;`.

    Anchored on the closing brace and scanning back to the nearest opening,
    because these enums are consecutive in the file and a forward
    non-greedy match would swallow all the preceding ones.
    """
    close = re.search(r'\}\s*' + name + r'\s*;', src)
    if not close:
        sys.exit('%s: enum %s not found' % (HEADER, name))
    start = src.rfind('typedef enum {', 0, close.start())
    if start < 0:
        sys.exit('%s: no opening brace for enum %s' % (HEADER, name))
    body = src[start + len('typedef enum {'):close.start()]
    # Drop comments before harvesting identifiers, so a commented-out member
    # or an EV_ mentioned in prose cannot become a probe.
    body = re.sub(r'/\*.*?\*/', ' ', body, flags=re.S)
    body = re.sub(r'//[^\n]*', ' ', body)
    return re.findall(r'\b(EV_[A-Z_0-9]+)\b', body)


def probe_name(ident, strip):
    """EV_MINOR_LOCAL_ROOTS -> minor_local_roots"""
    assert ident.startswith(strip), ident
    return ident[len(strip):].lower()


def main():
    if not os.path.exists(HEADER):
        sys.exit('run from the tree root: %s not found' % HEADER)
    src = open(HEADER).read()

    phases = enum_members(src, 'ev_runtime_phase')
    counters = enum_members(src, 'ev_runtime_counter')
    lifecycles = enum_members(src, 'ev_lifecycle')

    out = []
    w = out.append
    w('/* GENERATED by tools/gen_runtime_events_usdt.py -- DO NOT EDIT.')
    w(' * Regenerate after changing the enums in runtime_events.h. */')
    w('')
    w('#ifndef CAML_RUNTIME_EVENTS_USDT_H')
    w('#define CAML_RUNTIME_EVENTS_USDT_H')
    w('')
    w('/* USDT (SystemTap SDT) probes for the runtime event surface.')
    w(' *')
    w(' * Every probe is static and individually addressable: each call site')
    w(' * names its phase as a literal, so CAML_EV_BEGIN(EV_MINOR) pastes into a')
    w(' * probe called "minor_begin" rather than one generic probe taking the')
    w(' * phase as an argument. That is what lets a tracer attach to just the')
    w(' * probes it wants:')
    w(' *')
    w(' *   bpftrace -l \'usdt:./prog:%s:*\'            all probes' % PROVIDER)
    w(' *   bpftrace -l \'usdt:./prog:%s:minor*\'       minor-GC phases' % PROVIDER)
    w(' *   bpftrace -l \'usdt:./prog:%s:counter_*\'    counters' % PROVIDER)
    w(' *   bpftrace -l \'usdt:./prog:%s:lifecycle_*\'  lifecycle events' % PROVIDER)
    w(' *')
    w(' * When no tracer is attached each probe is a single 1-byte nop and')
    w(' * costs ~0.11 ns; arguments generate no marshalling code at all, their')
    w(' * locations being recorded in the ELF note. When attached, a hit costs')
    w(' * ~1.8 us (a uprobe trap), so probes must stay off any path that fires')
    w(' * at more than order 100k/s. See PLAN-ocaml-usdt.md step 0 for the')
    w(' * measurements behind those numbers.')
    w(' */')
    w('')
    w('#if defined(HAS_SYS_SDT_H) && !defined(CAML_DISABLE_USDT)')
    w('')
    w('#include <sys/sdt.h>')
    w('')
    w('#define CAML_USDT_ENABLED 1')
    w('')
    w('/* Two-level paste so the name-mapping macro below is expanded before')
    w(' * being glued to its _begin/_end suffix. */')
    w('#define CAML_USDT_CAT_(a, b) a##b')
    w('#define CAML_USDT_CAT(a, b) CAML_USDT_CAT_(a, b)')
    w('')
    w('/* Enum constant -> probe name stem. */')
    for p in phases:
        w('#define CAML_USDT_PHASE_%s %s' % (p, probe_name(p, 'EV_')))
    w('')
    for c in counters:
        w('#define CAML_USDT_COUNTER_%s counter_%s' % (c, probe_name(c, 'EV_C_')))
    w('')
    for l in lifecycles:
        w('#define CAML_USDT_LIFECYCLE_%s lifecycle_%s'
          % (l, probe_name(l, 'EV_')))
    w('')
    w('#define CAML_USDT_EV_BEGIN(p) \\')
    w('  STAP_PROBE(%s, CAML_USDT_CAT(CAML_USDT_PHASE_##p, _begin))' % PROVIDER)
    w('#define CAML_USDT_EV_END(p) \\')
    w('  STAP_PROBE(%s, CAML_USDT_CAT(CAML_USDT_PHASE_##p, _end))' % PROVIDER)
    w('#define CAML_USDT_EV_COUNTER(c, v) \\')
    w('  STAP_PROBE1(%s, CAML_USDT_CAT(CAML_USDT_COUNTER_##c, ), (v))'
      % PROVIDER)
    w('#define CAML_USDT_EV_LIFECYCLE(l, d) \\')
    w('  STAP_PROBE1(%s, CAML_USDT_CAT(CAML_USDT_LIFECYCLE_##l, ), (d))'
      % PROVIDER)
    w('')
    w('/* Dispatch for the one site that cannot name its counter as a')
    w(' * literal: realloc_generic_table() in minor_gc.c takes the counter as')
    w(' * a parameter, and its three callers pass three different ones. A')
    w(' * generated switch keeps every counter individually attachable rather')
    w(' * than collapsing those three into one generic probe. Only the arm')
    w(' * actually reached fires, and the site is cold (minor-GC table')
    w(' * growth), so the unreached nops cost nothing. */')
    w('#define CAML_USDT_EV_COUNTER_DYN(c, v) \\')
    w('  do { switch (c) { \\')
    for c in counters:
        w('    case %s: \\' % c)
        w('      CAML_USDT_EV_COUNTER(%s, (v)); break; \\' % c)
    w('    default: break; \\')
    w('  } } while (0)')
    w('')
    w('#else /* no <sys/sdt.h>, or USDT explicitly disabled */')
    w('')
    w('/* The arguments are still evaluated: a counter value or lifecycle')
    w(' * datum may be a call with side effects, and dropping it would change')
    w(' * behaviour rather than just remove instrumentation. */')
    w('#define CAML_USDT_EV_BEGIN(p)        ((void) 0)')
    w('#define CAML_USDT_EV_END(p)          ((void) 0)')
    w('#define CAML_USDT_EV_COUNTER(c, v)   ((void) (v))')
    w('#define CAML_USDT_EV_LIFECYCLE(l, d) ((void) (d))')
    w('#define CAML_USDT_EV_COUNTER_DYN(c, v) ((void) (c), (void) (v))')
    w('')
    w('#endif')
    w('')
    w('#endif /* CAML_RUNTIME_EVENTS_USDT_H */')

    text = '\n'.join(out) + '\n'
    if '--check' in sys.argv:
        cur = open(OUTPUT).read() if os.path.exists(OUTPUT) else ''
        if cur != text:
            sys.exit('%s is stale: re-run tools/gen_runtime_events_usdt.py'
                     % OUTPUT)
        print('%s is up to date (%d phases, %d counters, %d lifecycle)'
              % (OUTPUT, len(phases), len(counters), len(lifecycles)))
        return
    open(OUTPUT, 'w').write(text)
    print('wrote %s: %d phases (%d probes), %d counters, %d lifecycle '
          '= %d probes total'
          % (OUTPUT, len(phases), 2 * len(phases), len(counters),
             len(lifecycles),
             2 * len(phases) + len(counters) + len(lifecycles)))


if __name__ == '__main__':
    main()
